services:
  - type: web
    name: workout-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MONGODB_URI
        value: ${MONGODB_URI}
      - key: JWT_SECRET
        value: ${JWT_SECRET}
    plan: free
